### ISSUE TITLE
Owner Now Using a Full Emacs/Org-Mode based version of Soji

### ISSUE THREAD

**Issue by joecannatti** [joecannatti/soji#24]
Hi!

I'm the owner of this project.
I just wanted to give a status update to explain why I haven't been working on the codebase.
I have switched over to a Soji system that is based entirely on Emacs/Org-mode.

I've been using that version for some time.
I'm currently doing an independent study at a University on building web based views to access the Soji data as well.

As such, I don't use this bash based version of Soji anymore.
I can continue maintaining the repo, but if there is anyone who has really stuck with Soji and wants to maintain an official fork, I would endorse that plan of action.

Thanks!
Joe C

**Comment by agbrook** [comment]
I do like this system and I would ask you about what you're using now, but I'm not really interested in learning Emacs. :-) 

I am, however, interested in the web based views work you'll be doing. I'm working on a somewhat side project of getting the soji data back out of the logs to put them into a time worked system we're using here. Having a web based view of this data would make that process easier. 

The only big issue I can see is that I'm using this on a Mac instead of in Ubuntu. I think as long as it stays in bash, things should be okay? That being said, I'm interested in helping maintain this product as I'm finding it useful.

**Comment by joecannatti** [comment]
Sounds great Andy. I'll add you as a committer. You can have full control of this code base. The only thing I won't give is permission to change the license.

**Comment by joecannatti** [comment]
Ah, or you can fork it and I'll link from here to your repo. Whichever you prefer

**Comment by agbrook** [comment]
We can leave it here for now. If there ends up being a lot of work, maybe we can look at transferring the repo later. For now, I'm going to delete my fork and work in this repo.

**Comment by agbrook** [comment]
Last question and then we can probably close this issue: Why did you choose guile to run the main soji command?

**Comment by joecannatti** [comment]
haha, great question! :)

I wanted to rewrite the whole thing in a scripting language so that I wouldn't have to deal with all the crossplatform (and other) shell problems. I choose guile just because I wanted to play around with a Lisp language. This was long before I realized other people might actually want to use it :)

So it is now, I don't think the guile is really serving any purpose at all. You're probably best off to rip it out. If you go back through the git history, you should be able to find the old shell script version of that same file. Not sure it's still compatible, but would give you a starting point if you want to rip the guile out.

Again, it's your show now, so whatever you want to do, but that's the backstory.
